spring:
  profiles:
    active: local

server:
  port: 6060

---

spring:
  config:
    activate:
      on-profile:
        - local

  data:
    mongodb:
      host: localhost
      port: 27017
      database: local